# This workflow will build and deploy using Cloud Run.

name: Cloud Run Continuous Deployment

on:
  push:
    # TODO: change 'none' to 'main' to enable the workflow to run
    branches: 'main'
  release:
    types: [published]

env:
  # TODO: Paste output from setup.sh below.
  PROJECT_ID: 'jesus-munoz-ute'
  SERVICE_NAME: 'ise-lab2-cicd-the-manipulators-new'
  SERVICE_REGION: 'us-central1'
  SERVICE_ACCOUNT: '470475185603-compute@developer.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/470475185603/locations/global/workloadIdentityPools/github-provider/providers/github-project-repo'

jobs:
  py-checks:
    uses: ./.github/workflows/python-checks.yml
    
  build-deploy:
    name: 'Build and deploy using Cloud Run'
    runs-on: ubuntu-latest
    needs: py-checks

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'
    # Authorize GitHub to connect to your service account
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: '${{ env.SERVICE_ACCOUNT }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        version: '>= 363.0.0'

    - name: 'Configure docker for Artifact Registry'
      run: 'gcloud auth configure-docker ${{ env.SERVICE_REGION }}-docker.pkg.dev'

    - name: 'Build and push Docker image'
      uses: 'docker/build-push-action@v5'
      with:
        context: .
        push: true
        tags: '${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}'

    - id: 'Deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: '${{ env.SERVICE_NAME }}'
        image: '${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest'
        region: '${{ env.SERVICE_REGION }}'

    - name: 'Display deployed app URL'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
